name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
    
    - name: Update manifest version
      if: github.event_name == 'workflow_dispatch'
      run: |
        jq '.version = "${{ steps.get_version.outputs.VERSION_NUMBER }}"' manifest.json > manifest.tmp.json
        mv manifest.tmp.json manifest.json
        
    - name: Create distribution package
      run: |
        # Create a clean distribution directory
        mkdir -p dist
        
        # Copy all necessary files for the extension
        cp -r icons dist/
        cp -r docs dist/
        cp manifest.json dist/
        cp *.js dist/
        cp *.html dist/
        cp *.css dist/
        cp LICENSE dist/
        cp README.md dist/
        cp PRIVACY_JUSTIFICATIONS.md dist/
        
        # Create the zip file
        cd dist
        zip -r ../vdo-ninja-capture-extension.zip *
        cd ..
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## VDO.Ninja Video Capture Extension ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          1. Download `vdo-ninja-capture-extension.zip` below
          2. Extract the ZIP file to a folder
          3. Open Chrome/Edge and navigate to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ### What's Changed
          - See [commits](https://github.com/${{ github.repository }}/commits/${{ steps.get_version.outputs.VERSION }}) for details
          
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vdo-ninja-capture-extension.zip
        asset_name: vdo-ninja-capture-extension.zip
        asset_content_type: application/zip
